version: "3.7"
services:
    dFront_service:
       container_name: dfront-container
       image: nginx:1.20.1
       restart: always
       volumes:
         - .:/usr/share/nginx/html
       ports:
           - "9911:80"
