version: "3.7"
services:
    construccion_svc:
       container_name: construccion-container
       image: nginx:1.21.6
       restart: always
       volumes:
         - ./site:/usr/share/nginx/html
       ports:
           - "9911:80"
